name: Publish Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx (for multi-platform builds, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/d33p0st/modstore:latest
            ghcr.io/d33p0st/modstore:${{ github.sha }}
          platforms: linux/amd64  # Specify platforms as needed

      # Optional: Verify the image exists on ghcr.io
      - name: Verify Image
        run: |
          echo "Docker image published successfully:"
          echo "ghcr.io/d33p0st/modstore:latest"