name: Unit Tests

on:
    push:
        branches:
            - '*'
            - '*/*'
            - '**'

permissions: read-all

jobs:
    Test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
    
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Run PyTest
              uses: d33pster/automated-pytest@v2
              with:
                Library: "."